# Generated by Django 3.1.5 on 2021-01-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210125_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['id'], 'verbose_name': 'Schema', 'verbose_name_plural': 'Schemas'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['-created_at'], 'verbose_name': 'Schema', 'verbose_name_plural': 'Schemas'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Schema', 'verbose_name_plural': 'Schemas'},
        ),
    ]
