# Generated by Django 3.1.5 on 2021-01-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210125_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Error'),
        ),
    ]
