# Generated by Django 3.1.5 on 2021-01-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Error'), (5, 'In process'), (10, 'Completed')], default=5, verbose_name='Status'),
        ),
    ]
