# Generated by Django 3.1.5 on 2021-01-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='separator',
            field=models.CharField(choices=[(';', ';'), (',', ','), ('|', '|')], default=';', max_length=1, verbose_name='Separator'),
        ),
    ]
